spring.application.name=shoeshop

#turn off banner
spring.main.banner-mode=off

#reduce logging level to warn
logging.level.root=warn

#connect to MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/shoeshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

#Spring-data-path
spring.data.rest.base-path=/api

#Spring Security temp
spring.security.user.name=admin
spring.security.user.password=123456
# ?? t?m
app.jwt.secret=shoeshop-secret-key-super-long-2026
app.jwt.expiration-ms=86400000
#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danhv5879@gmail.com
spring.mail.password=xvyz uzli otlj viiz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true